name: Deploy to Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTH_GITHUB_TOKEN }}

      - name: Deploy and restart services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Install required dependencies
            npm install -g yarn
            npm install -g pm2

            # Navigate to project directory and update repository
            echo "Updating repository..."
            cd dc-university/
            ls -la
            git config --global --add safe.directory /dc-university
            git stash
            git pull https://${{ secrets.AUTH_GITHUB_TOKEN }}@github.com/DecentraSchool/dc-university.git master

            # Backend deployment
            echo "Deploying backend..."
            cd backend/
            yarn install
            pm2 restart backend

            # CMS deployment
            echo "Deploying CMS..."
            cd cms/
            yarn install
            pm2 restart cms

            # Restart Nginx
            echo "Restarting Nginx..."
            systemctl restart nginx

      - name: Deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deployment completed successfully"
          else
            echo "❌ Deployment failed"
          fi
