name: Auto Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP '
            # Deploy backend
            cd
            cd dc-university/backend/ &&
            git pull origin master &&
            yarn install &&
            pm2 restart backend &&

            # Deploy CMS
            cd
            cd dc-university/cms/ &&
            git pull origin master &&
            yarn install &&
            pm2 restart cms
          '