name: Auto Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          ssh -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP '
            
            # Deploy backend
            cd ~/dc-university/backend/ &&
            echo "Updating backend..." &&
            git pull origin master &&

            # Run install with increased memory limit and production flag
            
            yarn install &&
            pm2 restart backend &&

            # Deploy CMS
            cd ~/dc-university/cms/ &&
            echo "Updating CMS..." &&
            git pull origin master &&

            # Run install with increased memory limit and production flag
            
            NODE_OPTIONS="--max-old-space-size=8080" yarn install &&
            pm2 restart cms
          '
